apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-demo-app
  namespace: monitoring-demo
  labels:
    app: monitoring-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-demo-app
  template:
    metadata:
      labels:
        app: monitoring-demo-app
    spec:
      containers:
        - name: monitoring-demo-app
          image: monitoring-demo-app:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"