apiVersion: v1
kind: Service
metadata:
  name: self-healing-nodeport
  namespace: self-healing-demo
spec:
  type: NodePort
  selector:
    app: self-healing-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30087